version: "3.8"

services:
  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - LOCAL_NETWORK=${LOCAL_NETWORK:-"192.168.0.0/16"} 
    volumes:
      - ./vpn:/vpn

  hyperliquid-trading-bot:
    build:
      context: .
    container_name: hyperliquid-trading-bot
    network_mode: "service:vpn"  # This routes all traffic through the VPN container.
    restart: unless-stopped
    depends_on:
      - vpn
